<?php if($block->getHeurekaId()): ?>
<!-- Heureka.cz PRODUCT DETAIL script -->
<script>
    (function(t, r, a, c, k, i, n, g) {t['ROIDataObject'] = k;
        t[k]=t[k]||function(){(t[k].q=t[k].q||[]).push(arguments)},t[k].c=i;n=r.createElement(a),
            g=r.getElementsByTagName(a)[0];n.async=1;n.src=c;g.parentNode.insertBefore(n,g)
    })(window, document, 'script', '//www.heureka.cz/ocm/sdk.js?version=2&page=product_detail', 'heureka', 'cz');
</script>
<?php endif; ?>