<?php
    $heureka_id = $block->getHeurekaId();
    $orderData = $block->getOrderData();
?>

<script>
    (function(t, r, a, c, k, i, n, g) {t['ROIDataObject'] = k;
        t[k]=t[k]||function(){(t[k].q=t[k].q||[]).push(arguments)},t[k].c=i;n=r.createElement(a),
            g=r.getElementsByTagName(a)[0];n.async=1;n.src=c;g.parentNode.insertBefore(n,g)
    })(window, document, 'script', '//www.heureka.cz/ocm/sdk.js?version=2&page=thank_you', 'heureka', 'cz');
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "purchaseHeureka": {
                        "component": "Railsformers_MarketingPack/js/heureka/purchase",
                        "heurekaId": "<?php echo $heureka_id ?>",
                        "orderData": <?php echo json_encode($orderData); ?>
    }
}
}
}
}
</script>

