<?php
$g_id = $block->getGoogleAnalyticsId();
?>

<?php if ($g_id): ?>
    <script async src="https://www.googletagmanager.com/gtag/js?id=<?php echo $g_id ?>"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());
        gtag('config', '<?php echo $g_id ?>');
    </script>
<?php endif; ?>