<?php
$orderData = $block->getOrderData();
?>

<?php if($block->getGoogleAnalyticsId()): ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "purchaseGtag": {
                        "component": "Railsformers_MarketingPack/js/googleanalytics/purchase",
                        "orderData": <?php echo json_encode($orderData); ?>
    }
}
}
}
}
</script>
<?php endif; ?>