<?php
$clarity_id = $block->getClarityId();
?>

<?php if($clarity_id): ?>
<!-- Microsoft Clarity Script -->
<script type="text/javascript">
    require(['cookieManager'], function(cookieManager) {
        if (!cookieManager.isCategoryAllowed('analytics')) {
            console.log('Analytics storage consent not granted. Skipping Microsoft Clarity script.');
            return;
        }

        (function(c,l,a,r,i,t,y){
            c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
            t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
            y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
        })(window, document, "clarity", "script", "<?php echo $clarity_id ?>");
    });
</script>
<?php endif; ?>